global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres16:9187']

  - job_name: 'todo-list-app'
    static_configs:
      - targets: ['todo-list-app:8080']
