FROM openjdk:21-jdk as builder
WORKDIR /app/todo-list
COPY ./pom.xml /app
COPY ./todo-list/.mvn ./.mvn
COPY ./todo-list/mvnw .
COPY ./todo-list/pom.xml .
RUN ./mvnw clean package -Dmaven.test.skip -Dmaven.main.skip -Dspring-boot.repackage.skip && rm -r ./target/
COPY ./todo-list/src ./src
RUN ./mvnw clean package -DskipTests

FROM openjdk:21-jdk
WORKDIR /app
RUN mkdir ./logs
COPY --from=builder /app/todo-list/target/todo-list-1.0-SNAPSHOT.jar .
ARG PORT_APP=8081
ENV PORT $PORT_APP
EXPOSE $PORT
ENTRYPOINT ["java","-jar","./todo-list-1.0-SNAPSHOT.jar"]